// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BetterPickerExamples",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "BetterPickerExamples",
            targets: ["AppModule"],
            bundleIdentifier: "com.BetterPickerExamples",
            teamIdentifier: "F9PGNEMEHU",
            displayVersion: "1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "/Users/ericlewis/Developer/swiftui-betterpicker")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "BetterPicker", package: "swiftui-betterpicker")
            ],
            path: "."
        )
    ]
)